# This is a workflow to build and push a Docker image when Dockerfile changes
name: Build and Push Docker Image

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'  # Trigger only when Dockerfile changes
  pull_request:
    branches: [ main ]
    paths:
      - 'Dockerfile'
  workflow_dispatch:  # Allows manual triggering

# A workflow run is made up of one or more jobs
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}  # Push only on push, not PR
          tags: rickgoos/container:latest  # Replace with your Docker Hub repo